name: Manter App SASOA Ativo

on:
  schedule:
    # Executa a cada 6 horas todos os dias
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite disparar manualmente pelo botão do GitHub

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Acordar Streamlit via WebSocket / Sessão Real
        run: |
          curl -s -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          "https://questionario-sasoa-ggifjg43mxm57geif9oemy.streamlit.app/" > /dev/null
          echo "Sinal enviado com sucesso para a aplicação SASOA."
