name: Manter App SASOA Ativo

on:
  schedule:
    # Executa a cada 6 horas todos os dias
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit SASOA
        run: |
          curl -s -L --max-time 30 -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://questionario-sasoa-ggifjg43mxm57geif9oemy.streamlit.app/" || true
          echo "Sinal de ativação enviado com sucesso."
